categories = [
    "Household",
    "Clothes",
    "Healthcare",
    "Daily Use",
    "Drinks",
]

products = [
    {
        "id": 1,
        "title": "Ceramic Dinner Set",
        "category": "Household",
        "description": "Modern matte ceramic plates for everyday meals.",
        "price": 45.0,
        "image_url": "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=800&q=80",
        "rating": 4.8,
    },
    {
        "id": 2,
        "title": "Organic Cotton T-Shirt",
        "category": "Clothes",
        "description": "Soft, eco-friendly cotton tee with a relaxed fit.",
        "price": 28.0,
        "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
        "rating": 4.5,
    },
    {
        "id": 3,
        "title": "Daily Multivitamin",
        "category": "Healthcare",
        "description": "Complete vitamin pack to support everyday health.",
        "price": 19.5,
        "image_url": "https://images.unsplash.com/photo-1609137144813-56a0bb61ee42?auto=format&fit=crop&w=800&q=80",
        "rating": 4.7,
    },
    {
        "id": 4,
        "title": "Bamboo Toothbrushes",
        "category": "Daily Use",
        "description": "Eco-friendly toothbrush set for sustainable living.",
        "price": 12.0,
        "image_url": "https://images.unsplash.com/photo-1587854692152-cbe660dbde0e?auto=format&fit=crop&w=800&q=80",
        "rating": 4.6,
    },
    {
        "id": 5,
        "title": "Citrus Soda",
        "category": "Drinks",
        "description": "Refreshing sparkling soda with natural fruit flavor.",
        "price": 4.5,
        "image_url": "https://images.unsplash.com/photo-1554866585-36beb63c5655?auto=format&fit=crop&w=800&q=80",
        "rating": 4.3,
    },
    {
        "id": 6,
        "title": "Woven Storage Basket",
        "category": "Household",
        "description": "Versatile basket for shelves and decor.",
        "price": 32.0,
        "image_url": "https://images.unsplash.com/photo-1595531670456-abc20db7bd7e?auto=format&fit=crop&w=800&q=80",
        "rating": 4.4,
    },
    {
        "id": 7,
        "title": "Lightweight Hoodie",
        "category": "Clothes",
        "description": "Cozy everyday hoodie in neutral colors.",
        "price": 52.0,
        "image_url": "https://images.unsplash.com/photo-1556821552-5ff63ad14005?auto=format&fit=crop&w=800&q=80",
        "rating": 4.6,
    },
    {
        "id": 8,
        "title": "Hand Sanitizer",
        "category": "Healthcare",
        "description": "Non-drying formula for clean hands on the go.",
        "price": 9.0,
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80",
        "rating": 4.9,
    },
    {
        "id": 9,
        "title": "Reusable Water Bottle",
        "category": "Daily Use",
        "description": "Insulated bottle to keep drinks cold or hot.",
        "price": 22.5,
        "image_url": "https://images.unsplash.com/photo-1602143407151-7e06dc2b5fa2?auto=format&fit=crop&w=800&q=80",
        "rating": 4.7,
    },
    {
        "id": 10,
        "title": "Herbal Tea Pack",
        "category": "Drinks",
        "description": "Comforting herbal tea bundles for evening relaxation.",
        "price": 14.0,
        "image_url": "https://images.unsplash.com/photo-1597318972826-5f34c9fce0cf?auto=format&fit=crop&w=800&q=80",
        "rating": 4.8,
    },
    {
        "id": 11,
        "title": "Apple Juice",
        "category": "Drinks",
        "description": "Fresh apple juice blend, 100% natural.",
        "price": 5.99,
        "image_url": "https://images.unsplash.com/photo-1600271886742-f049cd1f3033?auto=format&fit=crop&w=800&q=80",
        "rating": 4.6,
    },
    {
        "id": 12,
        "title": "Winter Jacket",
        "category": "Clothes",
        "description": "Warm and durable winter jacket for cold weather.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1539533057686-5cc70adc92bf?auto=format&fit=crop&w=800&q=80",
        "rating": 4.8,
    },
]
